In [1]:
import FEM as fem
import numpy as np

E = 200e9
A = 0.01
l = 1
node1 = fem.Node(0 , 0 , u = 0 , v = 0)
node2 = fem.Node(l , 0 , Px = 0 , Py = -10e3)
node3 = fem.Node(0 , l , u = 0 , v = 0)
List = [node1 , node2 , node3]
sys = fem.SystemTruss(List)
sys.Connect(1 , 2 , E , A)
sys.Connect(2 , 3 , E , A)
sys.Generate()
print(sys.K/1e9)

Successfully Build The Truss System!
Successfully Generate Matrix K!
[[ 2.          0.         -2.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.        ]
 [-2.          0.          2.70710678 -0.70710678 -0.70710678  0.70710678]
 [ 0.          0.         -0.70710678  0.70710678  0.70710678 -0.70710678]
 [ 0.          0.         -0.70710678  0.70710678  0.70710678 -0.70710678]
 [ 0.          0.          0.70710678 -0.70710678 -0.70710678  0.70710678]]
