# P181-7-8

In [1]:
import FEM as fem
import numpy as np
NaN = np.nan

In [2]:
P = 24e3
a = 1
f = 0.01
E = 200e9
t = 0.01
G = E*f/t/a/10

node1 = fem.Node(-a , -a , Px = 0 , Py = 0)
node2 = fem.Node(0 , -a , Px = 0 , Py = 0)
node3 = fem.Node(a , -a , Px = 0 , Py = 0)
node4 = fem.Node(-a , 0 , Px = -P , v = 0)
node5 = fem.Node(0 , 0 , Px = 0 , Py = 0)
node6 = fem.Node(a , 0 , Px = P , v = 0)
node7 = fem.Node(-a , a , Px = 0 , Py = 0)
node8 = fem.Node(0 , a , Px = 0 , Py = 0)
node9 = fem.Node(a , a , Px = 0 , Py = 0)
nodelist = [node1 , node2 , node3 , node4 , node5 , node6 , node7 , node8 , node9]

In [3]:
sys = fem.SystemTruss(nodelist)

sys.Connect(1 , 2 , E , f)
sys.Connect(2 , 3 , E , f)
sys.Connect(4 , 5 , E , f)
sys.Connect(5 , 6 , E , f)
sys.Connect(7 , 8 , E , f)
sys.Connect(8 , 9 , E , f)
sys.Connect(1 , 4 , E , f)
sys.Connect(4 , 7 , E , f)
sys.Connect(2 , 5 , E , f)
sys.Connect(5 , 8 , E , f)
sys.Connect(3 , 6 , E , f)
sys.Connect(6 , 9 , E , f)

sys.SetSheet(1 , 2 , 5 , 4 , G , t)
sys.SetSheet(2 , 3 , 6 , 5 , G , t)
sys.SetSheet(4 , 5 , 8 , 7 , G , t)
sys.SetSheet(5 , 6 , 9 , 8 , G , t)

sys.Generate()

Successfully Build The Truss System!
Successfully Generate Matrix K!


In [4]:
print(np.floor(sys.K/1e7))

[[ 205.    5. -195.   -5.    0.    0.   -5.    5.   -5.   -5.    0.    0.
     0.    0.    0.    0.    0.    0.]
 [   5.  205.    5.   -5.    0.    0.   -5. -195.   -5.   -5.    0.    0.
     0.    0.    0.    0.    0.    0.]
 [-195.    5.  410.    0. -195.   -5.   -5.    5.  -10.    0.   -5.   -5.
     0.    0.    0.    0.    0.    0.]
 [  -5.   -5.    0.  210.    5.   -5.    5.   -5.    0. -190.   -5.   -5.
     0.    0.    0.    0.    0.    0.]
 [   0.    0. -195.    5.  205.   -5.    0.    0.   -5.    5.   -5.   -5.
     0.    0.    0.    0.    0.    0.]
 [   0.    0.   -5.   -5.   -5.  205.    0.    0.    5.   -5.    5. -195.
     0.    0.    0.    0.    0.    0.]
 [  -5.   -5.   -5.    5.    0.    0.  210.    0. -190.    0.    0.    0.
    -5.    5.   -5.   -5.    0.    0.]
 [   5. -195.    5.   -5.    0.    0.    0.  410.    0.  -10.    0.    0.
    -5. -195.   -5.   -5.    0.    0.]
 [  -5.   -5.  -10.    0.   -5.    5. -190.    0.  420.    0. -190.    0.
    -5.    5.  -10.   

In [5]:
sys.Solve()

In [6]:
print(sys.Report)

Reprort : Information of This Truss System

**************************************************
q of 1,2,5,4:
6065.843627920849 N/m

q of 2,3,6,5:
5957.685187014215 N/m

q of 4,5,8,7:
-1613.64534464764 N/m

q of 5,6,9,8:
-4499.375849184783 N/m

--------------------------------------------------
Node1 :
 Position :
(-1,-1)
External Load :
 Horizontal Load Px = 0.0 N
Vertical Load Py = 0.0 N
Displacement :
 Horizontal Displacement u = -4.57763671875e-05 m
Vertical Displacement v = 1.4642857142857145e-06 m
--------------------------------------------------
Node2 :
 Position :
(0,-1)
External Load :
 Horizontal Load Px = 0.0 N
Vertical Load Py = 0.0 N
Displacement :
 Horizontal Displacement u = -4.57763671875e-05 m
Vertical Displacement v = 1.0875657434942025e-06 m
--------------------------------------------------
Node3 :
 Position :
(1,-1)
External Load :
 Horizontal Load Px = 0.0 N
Vertical Load Py = 0.0 N
Displacement :
 Horizontal Displacement u = -1.52587890625e-05 m
Vertical Displace

In [7]:
ans=sys.InternalForce

In [8]:
ll = sys.SheetList

In [9]:
ll[3].ke/1e6

matrix([[ 50.,  50.,  50., -50., -50., -50., -50.,  50.],
        [ 50.,  50.,  50., -50., -50., -50., -50.,  50.],
        [ 50.,  50.,  50., -50., -50., -50., -50.,  50.],
        [-50., -50., -50.,  50.,  50.,  50.,  50., -50.],
        [-50., -50., -50.,  50.,  50.,  50.,  50., -50.],
        [-50., -50., -50.,  50.,  50.,  50.,  50., -50.],
        [-50., -50., -50.,  50.,  50.,  50.,  50., -50.],
        [ 50.,  50.,  50., -50., -50., -50., -50.,  50.]])

In [10]:
sys.PartK['0,1']/1e6

array([[ 2000.,     0., -2000.,     0.],
       [    0.,     0.,     0.,     0.],
       [-2000.,     0.,  2000.,     0.],
       [    0.,     0.,     0.,     0.]])

In [11]:
uv = np.linalg.inv(sys.K).dot(np.array([
    0,0,0,0,0,0,-P,0,0,0,P,0,0,0,0,0,0,0
]))

In [12]:
uv

array([-1.08480453e-05, -1.52215362e-05, -1.08480453e-05, -2.66283751e-05,
       -1.03116035e-05, -4.84585762e-05, -2.53915787e-05, -1.42008066e-05,
       -1.36792660e-05, -2.66283751e-05, -2.50339508e-06, -4.84585762e-05,
        1.34706497e-05, -1.03861094e-05,  9.92417336e-06, -3.22163105e-05,
        7.62939453e-06, -4.95910645e-05])

In [13]:
K = sys.K

In [14]:
IF = sys.InternalForce

In [15]:
sys.NodeConnection

array([[0., 1., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
(-3.221631050109863e-05+2.6628375053405762e-05)*12

-6.705522537231445e-05