# P295-11.6.3

In [1]:
import FEM as fem
import numpy as np
NaN = np.nan

In [2]:
P = 1e5
E = 200e9
a = 1
A = 0.01
t = 2.6*A/a
G = E/2.6

In [3]:
node1 = fem.Node(2*a , a , Px = P , Py = 0)
node2 = fem.Node(a , a , Px = 0 , Py = 0)
node3 = fem.Node(0 , a , Px = 0 , Py = 0)
node4 = fem.Node(2*a , 0 , u = 0 , v = 0)
node5 = fem.Node(a , 0 , u = 0 , v = 0)
node6 = fem.Node(0 , 0 , u = 0 , v = 0)
ListNode = [node1 , node2 , node3 , node4 , node5 , node6]
sys = fem.SystemTruss(ListNode)
sys.Connect(2 , 1 , E , A)
sys.Connect(3 , 2 , E , A)
sys.Connect(4 , 1 , E , A)
sys.Connect(5 , 2 , E , A)
sys.Connect(6 , 3 , E , A)
sys.SetSheet(6 , 5 , 2 , 3 , G , t)
sys.SetSheet(5 , 4 , 1 , 2 , G , t)
sys.Generate()
sys.Solve()

Successfully Build The Truss System!
Successfully Generate Matrix K!


In [4]:
print(np.round(sys.K/1e8/5))

[[ 5.  1. -3. -1.  0.  0. -1.  1. -1. -1.  0.  0.]
 [ 1.  5.  1. -1.  0.  0. -1. -3. -1. -1.  0.  0.]
 [-3.  1. 10.  0. -3. -1. -1.  1. -2.  0. -1. -1.]
 [-1. -1.  0.  6.  1. -1.  1. -1.  0. -2. -1. -1.]
 [ 0.  0. -3.  1.  5. -1.  0.  0. -1.  1. -1. -1.]
 [ 0.  0. -1. -1. -1.  5.  0.  0.  1. -1.  1. -3.]
 [-1. -1. -1.  1.  0.  0.  1. -1.  1.  1.  0.  0.]
 [ 1. -3.  1. -1.  0.  0. -1.  5. -1. -1.  0.  0.]
 [-1. -1. -2.  0. -1.  1.  1. -1.  2.  0.  1.  1.]
 [-1. -1.  0. -2.  1. -1.  1. -1.  0.  6. -1. -1.]
 [ 0.  0. -1. -1. -1.  1.  0.  0.  1. -1.  1.  1.]
 [ 0.  0. -1. -1. -1. -3.  0.  0.  1. -1.  1.  5.]]


In [5]:
sys.SheetList[1].q

62500.0

In [6]:
print(sys.Report)

Reprort : Information of This Truss System

**************************************************
q of 6,5,2,3:
37500.0 N/m

q of 5,4,1,2:
62500.0 N/m

--------------------------------------------------
Node1 :
 Position :
(2,1)
External Load :
 Horizontal Load Px = 100000.0 N
Vertical Load Py = 0.0 N
Displacement :
 Horizontal Displacement u = 5.937500000000001e-05 m
Vertical Displacement v = -1.5625e-05 m
--------------------------------------------------
Node2 :
 Position :
(1,1)
External Load :
 Horizontal Load Px = 0.0 N
Vertical Load Py = 0.0 N
Displacement :
 Horizontal Displacement u = 2.4999999999999998e-05 m
Vertical Displacement v = 6.250000000000003e-06 m
--------------------------------------------------
Node3 :
 Position :
(0,1)
External Load :
 Horizontal Load Px = 0.0 N
Vertical Load Py = 0.0 N
Displacement :
 Horizontal Displacement u = 1.5624999999999997e-05 m
Vertical Displacement v = 9.375000000000001e-06 m
--------------------------------------------------
Node4 :
 Po

In [7]:
print(np.round(sys.InternalForce))

[[     0. 100000.      0.      0.      0.      0.]
 [ 37500.      0.  37500.      0.      0.      0.]
 [     0.      0.      0.      0.      0.      0.]
 [-62500.      0.      0.      0. -31250.      0.]
 [     0.  25000.      0.  31250.      0. -18750.]
 [     0.      0.  37500.      0.  18750.      0.]]


In [8]:
sys.NodeConnection

array([[0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])