In [6]:
import FEM as fem
import numpy as np
NaN = np.nan

In [7]:
x = np.array([1,NaN , 3 , 4])
y = np.array([NaN,2 , NaN , NaN])
K = np.array([
    [1,2,3,4],
    [2,2,78,9],
    [4,5,2,3],
    [67,43,2,1]
])

In [8]:
xx,yy=fem.LinearSolve(K , x , y)

In [9]:
yy-K.dot(xx)

array([0., 0., 0., 0.])

In [10]:
np.zeros([3,4])+NaN

array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [18]:
a = np.array([1,2,3,4])
b = np.matrix(a)
b.T.dot(b)

matrix([[ 1,  2,  3,  4],
        [ 2,  4,  6,  8],
        [ 3,  6,  9, 12],
        [ 4,  8, 12, 16]])

In [22]:
K[0:2 , 1:3]


array([[ 2,  3],
       [ 2, 78]])

In [25]:
K[1,2]

78