# Python And Finity Element

这个寒假打算做点有意义的事情，比如说。。。学一学有限元？
用py写吧，感觉还是很有意思的哈哈哈！python真是个奇妙而又美丽的语言！

# 章一、python知识初步

## 1.类与继承
由于我有一定的python基础，这里就直接上有限元中一些重要的数据类型定义。比如需要定义一个节点类Node:
其中：需要包括结点受力$F_x,F_y$，结点位移$U_x,U_y$。

In [18]:
class Node:
    def __init__(self,x,y):
        # 定义节点类的初始化_init_()方法，传入参数节点坐标x和y
        #定义属性x,y代表节点的(x,y)坐标
        self.x=x
        self.y=y
        #定义节点力force，字典类型，key分别为"Fx",Fy"
        self.force={"Fx":0,"Fy":0}
        self.disp={"Ux":0,"Uy":0}
        pass
    #获取x，y坐标
    def get_x(self):
        return self.x
        pass
    def get_y(self):
        return self.y
        pass
    #设置x,y坐标
    def set_x(self,val):
        self.x=val
        pass
    def set_y(self,val):
        self.y=val
        pass
    pass

In [19]:
nd=Node(0,1)
print(nd.force)

{'Fx': 0, 'Fy': 0}


当然上述的方法是对于二维平面形式的节点定义，我们可以运用python的继承方式定义三维空间中的节点。

In [22]:
class Node3D(Node):#继承Node类
    def __init__(self,x,y,z):
        Node.__init__(self,x,y)
        #定义属性z代表节点z方向坐标
        self.z=z
        pass
    #定义z坐标
    def get_z(self):
        return self.z
        pass
    #设置z坐标
    def set_z(self,val):
        self.z
        pass

In [23]:
nd=Node3D(0,1,3)
print(nd.get_z())

3


## 2.Numpy的使用

虽然我在之前的学习中有接触过一定的numpy使用，但是总体不是特别完整。因此我尝试着在使用中学习。

In [27]:
import numpy as np
a=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6],[4,5,6,7]])
print(a)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [33]:
print("a的维度是：{}".format(a.shape))
print("一共有{}个元素位于其中".format(a.size))

a的维度是：(4, 4)
一共有16个元素位于其中


In [37]:
a.T#转置

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [38]:
a.reshape(8,2)

array([[1, 2],
       [3, 4],
       [2, 3],
       [4, 5],
       [3, 4],
       [5, 6],
       [4, 5],
       [6, 7]])

In [43]:
b=np.array([1,2,3,4])
print("行乘行：",a*b)
print('两矩阵乘积：',a.dot(b))

行乘行 [[ 1  4  9 16]
 [ 2  6 12 20]
 [ 3  8 15 24]
 [ 4 10 18 28]]
两矩阵乘积 [30 40 50 60]
