In [1]:
import scipy.optimize as op
import numpy as np

In [2]:
c = np.array([1,1])
A = np.array([
    [-1,-1]
])
b = np.array([-6])
bound = ((0 , 2),(0 , 2))
res = op.linprog(c , A_ub = A , b_ub = b , bounds = bound)

In [3]:
res.status

2

In [4]:
a = np.array([1,2,3,4 , 5 , 6])
b = a.reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
b.max(axis=0)

array([5, 6])

In [6]:
b.std(axis = 0)

array([1.63299316, 1.63299316])