In [1]:
import numpy as np
import xlrd
import xlwt

In [2]:
file = xlrd.open_workbook("附件2 近5年8家转运商的相关数据.xls")
sheet = file.sheet_by_index(0)
Number = 8
Week = 240
mat = np.zeros([Number , Week])
for j in range(Number):
    for i in range(Week):
        mat[j][i] = sheet.cell_value(rowx = j+1 , colx = i+1)
        pass
    pass

In [3]:
data = np.zeros([Number , 3])
for i in range(Number):
    data[i][0] = np.mean(mat[i])
    data[i][1] = np.std(mat[i])
    data[i][2] = data[i][0] + 2*data[i][1]
    pass
print(data)

[[1.90476917 0.65593151 3.21663218]
 [0.92137042 0.47944926 1.88026893]
 [0.09070208 0.34467828 0.78005865]
 [0.667455   1.4774245  3.62230399]
 [0.99939792 1.79313942 4.58567676]
 [0.489385   1.28913425 3.0676535 ]
 [2.07883333 1.43241832 4.94366997]
 [0.85453083 1.08629569 3.0271222 ]]


In [4]:
dat = np.zeros(Number)
for j in range(Number):
    tmp = list()
    for i in range(Week):
        if mat[j][i] < data[j][2]:
            tmp.append(mat[j][i])
            pass
        pass
    tmp = np.array(tmp)
    dat[j] = np.mean(tmp)
    pass
dat

array([1.84308553, 0.89472911, 0.06664748, 0.25200548, 0.31813561,
       0.13108455, 1.47698492, 0.61824493])