In [1]:
import Compound as cp
import numpy as np
a=cp.layer('HT3/5224')
a.info()

------------------------------------------------------------

name of the compound material is:  HT3/5224

E1:
 140.0  GPa

E2:
 8.6  GPa

G23:
 5.0  GPa

S:
 [[ 0.00714286 -0.0025      0.        ]
 [-0.0025      0.11627907  0.        ]
 [ 0.          0.          0.2       ]]  GPa^-1

Q:
 [[141.06148769   3.03282199   0.        ]
 [  3.03282199   8.66520567   0.        ]
 [  0.           0.           5.        ]]  GPa

v12= 0.35 

v21= 0.0215 

place angle= 0.0  degree

thickness t= 0 

placement hk= 0 

S_:
 [[ 0.00714286 -0.0025      0.        ]
 [-0.0025      0.11627907  0.        ]
 [ 0.          0.          0.2       ]]  GPa^-1

Q_:
 [[141.06148769   3.03282199   0.        ]
 [  3.03282199   8.66520567   0.        ]
 [  0.           0.           5.        ]]  GPa

------------------------------------------------------------



In [2]:
a.set_angle(np.pi/4)
a.info()

------------------------------------------------------------

name of the compound material is:  HT3/5224

E1:
 140.0  GPa

E2:
 8.6  GPa

G23:
 5.0  GPa

S:
 [[ 0.00714286 -0.0025      0.        ]
 [-0.0025      0.11627907  0.        ]
 [ 0.          0.          0.2       ]]  GPa^-1

Q:
 [[141.06148769   3.03282199   0.        ]
 [  3.03282199   8.66520567   0.        ]
 [  0.           0.           5.        ]]  GPa

v12= 0.35 

v21= 0.0215 

place angle= 45.0  degree

thickness t= 0 

placement hk= 0 

S_:
 [[ 0.00717681 -0.00251345 -0.00247651]
 [-0.00251345  0.11627201 -0.00051514]
 [-0.00247651 -0.00051514  0.19994621]]  GPa^-1

Q_:
 [[1.41013381e+02 3.05605249e+00 1.75445099e+00]
 [3.05605249e+00 8.66685131e+00 6.01812996e-02]
 [1.75445099e+00 6.01812996e-02 5.02323050e+00]]  GPa

------------------------------------------------------------



In [3]:
epsilon=np.array([0.005,-0.01,0.02])
sigma=a.Q.dot(epsilon)/1e6
sigma

array([674.97921862, -71.4879468 , 100.        ])

In [4]:
a.T_inv.dot(sigma)

array([672.09775037, -68.60647855, 110.19355052])

In [5]:
a.T_inv.dot(epsilon)

array([ 0.00444894, -0.00944894,  0.02019808])

# 例4.7

In [6]:
name='HT3/5224'
t=0.125
plate47=list()
theta=[45,-45,0,0,0,0,-45,45]
for i in range(len(theta)):
    tmp=cp.layer(name)
    tmp.set_t(t)
    tmp.set_angle(theta[i])
    plate47.append(tmp)
    pass
plate47=cp.plate(plate47)
plate47.info()

------------------------------------------------------------

the laminate's name is: this is a laminate
the number of layers: 8 

each layer's t is: [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125] 

total height is: 1.0 

angles of the layers are:
 [45, -45, 0, 0, 0, 0, -45, 45] 

thickness of the laryers are:
 [0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125, 0.125] 

the matrix of this laminate is :
 [[[9.25047860e+01 1.84904532e+01 0.00000000e+00 1.15630983e+01
   2.31130665e+00 0.00000000e+00]
  [1.84904532e+01 2.63066450e+01 0.00000000e+00 2.31130665e+00
   3.28833063e+00 0.00000000e+00]
  [0.00000000e+00 0.00000000e+00 2.04576312e+01 0.00000000e+00
   2.38418579e-16 2.55720390e+00]]

 [[1.15630983e+01 2.31130665e+00 0.00000000e+00 6.11932559e+00
   2.79588638e+00 7.75759465e-01]
  [2.31130665e+00 3.28833063e+00 0.00000000e+00 2.79588638e+00
   3.70585170e+00 7.75759465e-01]
  [0.00000000e+00 2.38418579e-16 2.55720390e+00 7.75759465e-01
   7.75759465e-01 2.99055503e+00]]

In [7]:
plate47.info_detailed()

the 1 layer
------------------------------------------------------------

name of the compound material is:  HT3/5224

E1:
 140.0  GPa

E2:
 8.6  GPa

G23:
 5.0  GPa

S:
 [[ 0.00714286 -0.0025      0.        ]
 [-0.0025      0.11627907  0.        ]
 [ 0.          0.          0.2       ]]  GPa^-1

Q:
 [[141.06148769   3.03282199   0.        ]
 [  3.03282199   8.66520567   0.        ]
 [  0.           0.           5.        ]]  GPa

v12= 0.35 

v21= 0.0215 

place angle= 2578.3100780887044  degree

thickness t= 0.125 

placement hk= 0.625 

S_:
 [[ 0.07960548 -0.02039452 -0.05456811]
 [-0.02039452  0.07960548 -0.05456811]
 [-0.05456811 -0.05456811  0.12842193]]  GPa^-1

Q_:
 [[43.94808433 33.94808433 33.09907051]
 [33.94808433 43.94808433 33.09907051]
 [33.09907051 33.09907051 35.91526235]]  GPa

------------------------------------------------------------

the 2 layer
------------------------------------------------------------

name of the compound material is:  HT3/5224

E1:
 140.0  G