In [1]:
import FEM as fem
import numpy as np

<div aligned = "center"><img src="myFEM.png"></img></div>

In [2]:
E = 200e9
A1 = 1e-4
l1 = 20e-2
A2 = A1 * np.sqrt(2)/2
l2 = np.sqrt(2) * l1

#以节点4为(0,0)原点,设置点集信息
node1 = fem.Node(l1 , l1)
node2 = fem.Node(l1 , 0)
node3 = fem.Node(0 , l1)
node4 = fem.Node(0 , 0)

#系统建立，将节点类以list列表输入
nodeList = [node1 , node2 , node3 , node4]
sys = fem.SysPole(nodeList)

successfully build system!


In [3]:
#节点连接，展示连接矩阵
sys.connect(3 , 1 , E , A1)
sys.connect(4 , 1 , E , A2)
sys.connect(1 , 2 , E , A1)
sys.connect(3 , 2 , E , A2)
sys.connect(4 , 2 , E , A1)
sys.connect(3 , 4 , E , A1)

In [4]:
#连接矩阵，含带方向，共六根杆
sys.NodeConnection

array([[0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 1.],
       [1., 1., 0., 0.]])

In [5]:
#系统生成，组装刚度矩阵
sys.generate()

successfully get matrix K


In [6]:
#展示系统刚度矩阵，考虑单位换算后，结果与书本上一致
print(sys.K/0.25/1e6)

[[ 500.  100.    0.    0. -400.    0. -100. -100.]
 [ 100.  500.    0. -400.    0.    0. -100. -100.]
 [   0.    0.  500. -100. -100.  100. -400.    0.]
 [   0. -400. -100.  500.  100. -100.    0.    0.]
 [-400.    0. -100.  100.  500. -100.    0.    0.]
 [   0.    0.  100. -100. -100.  500.    0. -400.]
 [-100. -100. -400.    0.    0.    0.  500.  100.]
 [-100. -100.    0.    0.    0. -400.  100.  500.]]


In [19]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [21]:
1 in a

True