In [1]:
import numpy as np

In [2]:
def Kpole(E = 200e9 , A = 0.01 , l = 1):
    mat = np.array([
        [1 , -1],
        [-1 , 1]
    ])
    K = E * A / l * mat
    return K
    pass

In [3]:
def Direction(theta = 0):
    lambda1 = np.cos(theta)
    lambda2 = np.sin(theta)
    mat = np.array([
        [lambda1 , lambda2 , 0 , 0],
        [0 , 0 , lambda1 ,lambda2]
        ])
    return mat
    pass

In [4]:
def getK(E = 200e9 , A = 0.01 , l = 1 , theta = 0):
    K0 = Kpole(E,A,l)
    lam = Direction(theta)
    K = lam.T.dot(K0).dot(lam)
    return K
    pass

In [5]:
K12 = getK(theta = 0 , l = 1)
K23 = getK(theta = np.pi * 3 /4 , l = np.sqrt(2))
K31 = getK(theta = - np.pi / 2 , l = 1)

In [6]:
print(K12)
print(K23)
print(K31)

[[ 2.e+09  0.e+00 -2.e+09  0.e+00]
 [ 0.e+00  0.e+00  0.e+00  0.e+00]
 [-2.e+09  0.e+00  2.e+09  0.e+00]
 [ 0.e+00  0.e+00  0.e+00  0.e+00]]
[[ 7.07106781e+08 -7.07106781e+08 -7.07106781e+08  7.07106781e+08]
 [-7.07106781e+08  7.07106781e+08  7.07106781e+08 -7.07106781e+08]
 [-7.07106781e+08  7.07106781e+08  7.07106781e+08 -7.07106781e+08]
 [ 7.07106781e+08 -7.07106781e+08 -7.07106781e+08  7.07106781e+08]]
[[ 7.49879891e-24 -1.22464680e-07 -7.49879891e-24  1.22464680e-07]
 [-1.22464680e-07  2.00000000e+09  1.22464680e-07 -2.00000000e+09]
 [-7.49879891e-24  1.22464680e-07  7.49879891e-24 -1.22464680e-07]
 [ 1.22464680e-07 -2.00000000e+09 -1.22464680e-07  2.00000000e+09]]
